### ISSUE TITLE
The "global" command is not available. Make sure it is on PATH

### ISSUE THREAD

**Issue by EdZava** [alefragnani/vscode-language-pascal#21]
Every time you open a .pas file this warning comes out in the visual studio code.
I had to uninstall the plugin because it was very annoying.

**Comment by alefragnani** [comment]
Hi @EdZava ,

This happens because it _expects_ you to have **GNU Global** [installed and configured](https://github.com/alefragnani/vscode-language-pascal#installing-and-configuring-gnu-global). This _should not_ be assumed, and sure, should be fixed.

Thanks for reporting.

**Comment by alefragnani** [comment]
🏃 
I will look at this starting tomorrow. 
Stay tuned for the fix.

**Comment by m93a** [comment]
I'm still getting this message on a fresh installation of VS Code and Language Pascal extension downloaded in-app.

**Comment by alefragnani** [comment]
Hi @m93a , 

The message still exists, but now you can select what to do with two buttons added to the message:

* `More Info`: It will show you the `readme` with the instructions on how to setup `ctags/global`
* `Don't show again`: If you don't want to be bothered about that anymore

Hope this helps

**Comment by bilogic** [comment]
Can explain what's the benefit of ```ctags/global``` and impact of ```Don't show again```?

**Comment by alefragnani** [comment]
Hi @bilogic ,

Using `ctags/global` gives you what VS Code calls **Code Navigation** (described [here](https://code.visualstudio.com/docs/editor/editingevolved). This extension provides [some of them](features listed in https://github.com/alefragnani/vscode-language-pascal#code-navigation).

If you select `Don't show again`, it will not _check_ if `ctags/global` are installed, and you will be limited to **Syntax Highlighting**, **Formatter** and **Snippets**.

Hope this helps

**Comment by rjdunnill-atwork** [comment]
This is still happening on Windows.

**Comment by JimLynchCodes** [comment]
This is still happening on mac too... 😞

**Comment by Zephni** [comment]
Still happening for me too on Windows.

**Comment by alefragnani** [comment]
Hi,

For those of you where the message is still shown, may I assume you don't have `ctags` and `global` installed and available in `PATH`, right? 

If that's the case, and you don't need/want **code navigation** as commented [above](https://github.com/alefragnani/vscode-language-pascal/issues/21#issuecomment-504243597), you should click the `Don't show again` button in that message, as this should stop displaying that message.

If not, please open a new issue with more details about your `ctags` and `global` setup.

Hope this helps
